Fix default portfile location
aaronjensen/eslintd-fix pull request #19
Opened 2021-05-11 20:12 UTC by DamienCassou

eslint_d changed the location of the `.eslint_d` file that eslintd-fix uses to connect to the server. See https://github.com/mantoni/eslint_d.js/issues/166#issuecomment-838374082.

2021-05-12 02:00 UTC, aaronjensen requested changes
Thank you! Let's go ahead and support only 26 and up.

2021-05-12 02:00 UTC, aaronjensen commented on eslintd-fix.el
> +  ;; TODO: when using Emacs >= 26 as minimum Emacs requirement, switch
I'm fine supporting only 26 and up.

2021-05-12 07:27 UTC, DamienCassou commented on eslintd-fix.el
> +  ;; TODO: when using Emacs >= 26 as minimum Emacs requirement, switch
I updated my PR accordingly.

2021-05-13 04:24 UTC, aaronjensen commented
Thank you!

2021-05-13 04:24 UTC, merged